pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo 'Building application'
            }
        }

        stage('Test') {
            steps {
                sh 'echo Running tests'
            }
        }

        stage('Approve') {
            steps {
                input message: 'Tests passed. Deploy to production?'
            }
        }

        stage('Deploy') {
            steps {
                sh 'echo Deploying to production'
            }
        }
    }
}
