pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building application'
            }
        }

        stage('Tests') {
            parallel {
                stage('Unit') {
                    steps {
                        sh 'echo Running unit tests'
                    }
                }

                stage('Integration') {
                    steps {
                        sh 'echo Running integration tests'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application'
            }
        }
    }
}
